spring.application.name=companion

spring.datasource.url=jdbc:postgresql://localhost:5432/companion
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update